import { BaseNode, nodeType, objectId } from '@pascal-app/core'
import { z } from 'zod'
export const SHOWER_CONTROL = 'bath-space:shower-control'
export const ShowerControlNode = BaseNode.extend({
  id: objectId('bath-space-shower-control'),
  type: nodeType(SHOWER_CONTROL),
  children: z.array(z.string()).default([]),
  wallId: z.string().nullable().default(null),
  position: z
    .tuple([z.number().finite(), z.number().finite(), z.number().finite()])
    .default([0, 1.1, 0]),
  rotation: z.number().finite().default(0),
  side: z.enum(['front', 'back']).default('front'),
  mountingHeight: z.number().finite().min(0.5).max(3.5).default(1.1),
  tubeSize: z.number().finite().min(0.02).max(0.07).default(0.04),
  flangeEnabled: z.boolean().default(true),
  flangeSize: z.number().finite().min(0.08).max(0.6).default(0.16),
  flangeThickness: z.number().finite().min(0.003).max(0.02).default(0.006),
  layout: z.enum(['single', 'dual', 'buttons', 'bar', 'bridge', 'bath-single']).default('single'),
  function: z.enum(['mixer', 'diverter', 'flow']).default('mixer'),
  plateShape: z.enum(['round', 'square', 'rectangle', 'soft-rectangle']).default('round'),
  plateWidth: z.number().finite().min(0.08).max(0.36).default(0.16),
  plateHeight: z.number().finite().min(0.08).max(0.45).default(0.16),
  handleShape: z.enum(['round', 'square']).default('round'),
  handleStyle: z.enum(['lever', 'cross', 'knob']).default('lever'),
  handleDiameter: z.number().finite().min(0.02).max(0.07).default(0.042),
  handleLength: z.number().finite().min(0.025).max(0.1).default(0.06),
  handleProjection: z.number().finite().min(0.025).max(0.1).default(0.055),
  handleAngle: z.number().finite().min(-180).max(180).default(0),
  secondaryAngle: z.number().finite().min(-180).max(180).default(0),
  controlSpacing: z.number().finite().min(0.04).max(0.2).default(0.09),
  buttonCount: z.number().int().min(1).max(3).default(2),
  outletCount: z.number().int().min(1).max(3).default(2),
  selectedOutlet: z.number().int().min(1).max(3).default(1),
  bodyWidth: z.number().finite().min(0.18).max(0.45).default(0.3),
  inletSpacing: z.number().finite().min(0.1).max(0.24).default(0.15),
  projection: z.number().finite().min(0.05).max(0.2).default(0.09),
  hoseOutletEnabled: z.boolean().default(false),
  spoutEnabled: z.boolean().default(false),
  spoutStyle: z
    .enum([
      'round-straight',
      'round-curved',
      'round-arched',
      'square-straight',
      'square-angled',
      'waterfall-open',
      'waterfall-closed',
    ])
    .default('round-curved'),
  spoutLength: z.number().finite().min(0.08).max(0.4).default(0.18),
  spoutDrop: z.number().finite().min(0.01).max(0.15).default(0.045),
  spoutRise: z.number().finite().min(0.02).max(0.18).default(0.08),
  spoutWidth: z.number().finite().min(0.06).max(0.3).default(0.12),
  spoutHeight: z.number().finite().min(0.012).max(0.05).default(0.024),
  spoutSlope: z.number().finite().min(0).max(20).default(5),
  spoutSwivel: z.number().finite().min(-90).max(90).default(0),
  spoutAerator: z.boolean().default(true),
  bathDiverterStyle: z.enum(['pull-up', 'button']).default('pull-up'),
  bathDiverterRaised: z.boolean().default(false),
  riserEnabled: z.boolean().default(true),
  riserHeight: z.number().finite().min(0.03).max(0.2).default(0.115),
  markingsEnabled: z.boolean().default(true),
  slots: z.record(z.string(), z.string()).optional(),
})
export type ShowerControlNode = z.infer<typeof ShowerControlNode>
export const exposedControl = (n: ShowerControlNode) =>
  n.layout === 'bar' || n.layout === 'bridge' || n.layout === 'bath-single'
export const controlFootprint = (n: ShowerControlNode) =>
  exposedControl(n)
    ? n.bodyWidth + n.handleDiameter
    : Math.max(
        n.plateWidth,
        n.plateShape === 'round' || n.plateShape === 'square' ? n.plateWidth : n.plateHeight,
      )
export const showerControlPresets = [
  {
    id: 'round-lever',
    label: 'Round single-lever mixer',
    function: 'mixer',
    plateShape: 'round',
    layout: 'single',
    handleStyle: 'lever',
  },
  {
    id: 'square-lever',
    label: 'Square single-lever mixer',
    function: 'mixer',
    plateShape: 'square',
    layout: 'single',
    handleStyle: 'lever',
  },
  {
    id: 'dual-round',
    label: 'Twin round thermostat',
    function: 'mixer',
    plateShape: 'round',
    layout: 'dual',
    handleStyle: 'knob',
    plateWidth: 0.22,
    plateHeight: 0.22,
  },
  {
    id: 'dual-square',
    label: 'Twin rectangular thermostat',
    function: 'mixer',
    plateShape: 'rectangle',
    layout: 'dual',
    handleShape: 'square',
    handleStyle: 'knob',
    plateWidth: 0.13,
    plateHeight: 0.24,
  },
  {
    id: 'button-trim',
    label: 'Push-button thermostat',
    function: 'mixer',
    plateShape: 'soft-rectangle',
    layout: 'buttons',
    handleStyle: 'knob',
    plateWidth: 0.18,
    plateHeight: 0.2,
  },
  {
    id: 'bar-round',
    label: 'Round exposed thermostat',
    function: 'mixer',
    layout: 'bar',
    handleStyle: 'knob',
    hoseOutletEnabled: true,
    flangeSize: 0.35,
  },
  {
    id: 'bar-square',
    label: 'Square exposed thermostat',
    function: 'mixer',
    layout: 'bar',
    plateShape: 'square',
    handleShape: 'square',
    handleStyle: 'knob',
    hoseOutletEnabled: true,
    flangeSize: 0.35,
  },
  {
    id: 'bridge-cross',
    label: 'Two-handle exposed mixer',
    function: 'mixer',
    layout: 'bridge',
    handleStyle: 'cross',
    hoseOutletEnabled: true,
    flangeSize: 0.35,
  },
  {
    id: 'round-diverter',
    label: 'Round diverter trim',
    function: 'diverter',
    plateShape: 'round',
    handleStyle: 'lever',
    plateWidth: 0.1,
  },
  {
    id: 'square-diverter',
    label: 'Square diverter trim',
    function: 'diverter',
    plateShape: 'square',
    handleShape: 'square',
    handleStyle: 'knob',
    plateWidth: 0.1,
  },
  {
    id: 'round-flow',
    label: 'Round volume control',
    function: 'flow',
    plateShape: 'round',
    handleStyle: 'cross',
    plateWidth: 0.1,
    outletCount: 1,
  },
  {
    id: 'square-flow',
    label: 'Square stop control',
    function: 'flow',
    plateShape: 'square',
    handleStyle: 'lever',
    plateWidth: 0.1,
    outletCount: 1,
  },
  {
    id: 'bath-bridge-round',
    label: 'Round two-handle bath mixer',
    function: 'mixer',
    layout: 'bridge',
    handleStyle: 'cross',
    spoutEnabled: true,
    hoseOutletEnabled: true,
    spoutStyle: 'round-curved',
  },
  {
    id: 'bath-bridge-square',
    label: 'Square two-handle bath mixer',
    function: 'mixer',
    layout: 'bridge',
    plateShape: 'square',
    handleStyle: 'lever',
    spoutEnabled: true,
    hoseOutletEnabled: true,
    spoutStyle: 'square-straight',
  },
  {
    id: 'bath-single-round',
    label: 'Round single-lever bath mixer',
    function: 'mixer',
    layout: 'bath-single',
    handleStyle: 'lever',
    spoutEnabled: true,
    hoseOutletEnabled: true,
    spoutStyle: 'round-straight',
    riserEnabled: false,
  },
  {
    id: 'bath-single-square',
    label: 'Square single-lever bath mixer',
    function: 'mixer',
    layout: 'bath-single',
    plateShape: 'square',
    handleShape: 'square',
    handleStyle: 'lever',
    spoutEnabled: true,
    hoseOutletEnabled: true,
    spoutStyle: 'square-angled',
    riserEnabled: false,
  },
  {
    id: 'bath-thermostat',
    label: 'Thermostatic bath mixer',
    function: 'mixer',
    layout: 'bar',
    handleStyle: 'knob',
    spoutEnabled: true,
    hoseOutletEnabled: true,
    spoutStyle: 'round-curved',
    riserEnabled: false,
  },
  {
    id: 'bath-waterfall',
    label: 'Waterfall three-way wall mixer',
    function: 'mixer',
    layout: 'bridge',
    plateShape: 'square',
    handleStyle: 'knob',
    handleShape: 'square',
    spoutEnabled: true,
    hoseOutletEnabled: true,
    spoutStyle: 'waterfall-closed',
    bathDiverterStyle: 'button',
  },
] as const

export function controlPresetNode(p: (typeof showerControlPresets)[number]) {
  const { id, label, ...parameters } = p
  const node = ShowerControlNode.parse({ ...parameters, name: label })
  return { ...node, flangeSize: controlFootprint(node) }
}
export function controlPresetParameters(p: (typeof showerControlPresets)[number]) {
  const {
    id,
    type,
    object,
    parentId,
    children,
    wallId,
    position,
    rotation,
    side,
    mountingHeight,
    metadata,
    visible,
    name,
    slots,
    ...parameters
  } = controlPresetNode(p)
  return parameters
}
