import { BaseNode, nodeType, objectId } from '@pascal-app/core'
import { z } from 'zod'
export const FLOOR_STANDING_TOILET = 'bath-space:floor-standing-toilet'
const metres = (min: number, max: number, value: number) =>
  z.number().finite().min(min).max(max).default(value)
export const FloorStandingToiletNode = BaseNode.extend({
  supportSlabId: z.string().optional(),
  id: objectId('bath-space-floor-standing-toilet'),
  type: nodeType(FLOOR_STANDING_TOILET),
  design: z
    .enum([
      'back-to-wall',
      'compact-back-to-wall',
      'square-back-to-wall',
      'close-coupled',
      'one-piece',
      'traditional',
      'two-piece-round',
      'two-piece-elongated',
      'two-piece-skirted',
      'two-piece-classic',
      'one-piece-compact',
      'one-piece-low-profile',
      'one-piece-square',
      'one-piece-sculpted',
    ])
    .default('back-to-wall'),
  construction: z.enum(['two-piece', 'one-piece']).optional(),
  tankCornerRadius: metres(0.002, 0.045, 0.015),
  tankTaper: metres(0, 0.25, 0),
  tankLidThickness: metres(0.008, 0.035, 0.018),
  couplingGap: metres(0.005, 0.06, 0.015),
  baseStyle: z.enum(['skirted', 'pedestal']).default('skirted'),
  baseWidth: metres(0.18, 0.44, 0.3),
  baseDepth: metres(0.28, 0.7, 0.46),
  children: z.array(z.string()).default([]),
  wallId: z.string().nullable().default(null),
  position: z
    .tuple([z.number().finite(), z.number().finite(), z.number().finite()])
    .default([0, 0.4, 0]),
  rotation: z.number().finite().default(0),
  side: z.enum(['front', 'back']).default('front'),
  style: z.enum(['rounded', 'd-shaped', 'square', 'compact', 'elongated']).default('d-shaped'),
  width: metres(0.32, 0.48, 0.36),
  depth: metres(0.42, 0.75, 0.54),
  height: metres(0.22, 0.38, 0.3),
  mountingHeight: metres(0.36, 0.5, 0.4),
  wallThickness: metres(0.012, 0.035, 0.02),
  taper: metres(0, 0.45, 0.24),
  seatThickness: metres(0.012, 0.04, 0.022),
  seatEnabled: z.boolean().default(true),
  lidEnabled: z.boolean().default(true),
  lidOpen: z.boolean().default(false),
  rimless: z.boolean().default(true),
  tankType: z.enum(['concealed', 'attached', 'low-level', 'high-level']).default('concealed'),
  tankWidth: metres(0.28, 0.55, 0.36),
  tankDepth: metres(0.12, 0.24, 0.16),
  tankHeight: metres(0.28, 0.5, 0.36),
  tankBottom: metres(0.5, 1.9, 0.85),
  flushControlsSeparated: z.boolean().default(true),
  pipeDiameter: metres(0.035, 0.06, 0.045),
  slots: z.record(z.string(), z.string()).optional(),
}).refine((n) => n.height <= n.mountingHeight - 0.02 + 1e-9, {
  message: 'Bowl must leave room for the floor support',
  path: ['height'],
})
export type FloorStandingToiletNode = z.infer<typeof FloorStandingToiletNode>
export const toiletPresets = [
  {
    design: 'back-to-wall',
    construction: 'two-piece',
    tankCornerRadius: 0.015,
    tankTaper: 0,
    tankLidThickness: 0.018,
    couplingGap: 0.015,
    style: 'd-shaped',
    label: 'Back-to-wall',
    depth: 0.54,
    taper: 0.16,
    tankType: 'concealed',
    baseStyle: 'skirted',
  },
  {
    design: 'compact-back-to-wall',
    construction: 'two-piece',
    tankCornerRadius: 0.015,
    tankTaper: 0,
    tankLidThickness: 0.018,
    couplingGap: 0.015,
    style: 'compact',
    label: 'Compact back-to-wall',
    depth: 0.46,
    taper: 0.2,
    tankType: 'concealed',
    baseStyle: 'skirted',
  },
  {
    design: 'square-back-to-wall',
    construction: 'two-piece',
    tankCornerRadius: 0.015,
    tankTaper: 0,
    tankLidThickness: 0.018,
    couplingGap: 0.015,
    style: 'square',
    label: 'Square back-to-wall',
    depth: 0.54,
    taper: 0.08,
    tankType: 'concealed',
    baseStyle: 'skirted',
  },
  {
    design: 'close-coupled',
    construction: 'two-piece',
    tankCornerRadius: 0.015,
    tankTaper: 0,
    tankLidThickness: 0.018,
    couplingGap: 0.015,
    style: 'rounded',
    label: 'Close-coupled',
    depth: 0.54,
    taper: 0.28,
    tankType: 'attached',
    baseStyle: 'pedestal',
  },
  {
    design: 'one-piece',
    construction: 'one-piece',
    tankCornerRadius: 0.025,
    tankTaper: 0,
    tankLidThickness: 0.018,
    couplingGap: 0.015,
    style: 'elongated',
    label: 'One-piece',
    depth: 0.6,
    taper: 0.12,
    tankType: 'attached',
    baseStyle: 'skirted',
  },
  {
    design: 'traditional',
    construction: 'two-piece',
    tankCornerRadius: 0.015,
    tankTaper: 0,
    tankLidThickness: 0.018,
    couplingGap: 0.015,
    style: 'rounded',
    label: 'Traditional pedestal',
    depth: 0.56,
    taper: 0.3,
    tankType: 'low-level',
    baseStyle: 'pedestal',
  },
  {
    design: 'two-piece-round',
    label: 'Two-piece round',
    construction: 'two-piece',
    style: 'rounded',
    width: 0.36,
    depth: 0.49,
    baseDepth: 0.42,
    baseWidth: 0.28,
    baseStyle: 'pedestal',
    taper: 0.28,
    tankType: 'attached',
    tankWidth: 0.4,
    tankHeight: 0.37,
    tankDepth: 0.18,
    tankCornerRadius: 0.018,
    tankTaper: 0.1,
    tankLidThickness: 0.02,
    couplingGap: 0.025,
  },
  {
    design: 'two-piece-elongated',
    label: 'Two-piece elongated',
    construction: 'two-piece',
    style: 'elongated',
    width: 0.37,
    depth: 0.61,
    mountingHeight: 0.46,
    baseWidth: 0.29,
    baseDepth: 0.48,
    baseStyle: 'pedestal',
    taper: 0.25,
    tankType: 'attached',
    tankWidth: 0.41,
    tankHeight: 0.36,
    tankDepth: 0.18,
    tankCornerRadius: 0.02,
    tankTaper: 0.08,
    tankLidThickness: 0.022,
    couplingGap: 0.022,
  },
  {
    design: 'two-piece-skirted',
    label: 'Two-piece skirted',
    construction: 'two-piece',
    style: 'd-shaped',
    width: 0.37,
    depth: 0.56,
    baseWidth: 0.33,
    baseDepth: 0.5,
    baseStyle: 'skirted',
    taper: 0.08,
    tankType: 'attached',
    tankWidth: 0.37,
    tankHeight: 0.36,
    tankDepth: 0.16,
    tankCornerRadius: 0.012,
    tankTaper: 0,
    tankLidThickness: 0.016,
    couplingGap: 0.018,
  },
  {
    design: 'two-piece-classic',
    label: 'Two-piece classic',
    construction: 'two-piece',
    style: 'rounded',
    width: 0.38,
    depth: 0.56,
    baseWidth: 0.31,
    baseDepth: 0.46,
    baseStyle: 'pedestal',
    taper: 0.32,
    tankType: 'attached',
    tankWidth: 0.45,
    tankHeight: 0.4,
    tankDepth: 0.2,
    tankCornerRadius: 0.008,
    tankTaper: 0.2,
    tankLidThickness: 0.03,
    couplingGap: 0.035,
  },
  {
    design: 'one-piece-compact',
    label: 'One-piece compact',
    construction: 'one-piece',
    style: 'compact',
    width: 0.36,
    depth: 0.46,
    baseWidth: 0.31,
    baseDepth: 0.42,
    baseStyle: 'skirted',
    taper: 0.1,
    tankType: 'attached',
    tankWidth: 0.36,
    tankHeight: 0.3,
    tankDepth: 0.15,
    tankCornerRadius: 0.03,
    tankTaper: 0.08,
    tankLidThickness: 0.012,
  },
  {
    design: 'one-piece-low-profile',
    label: 'One-piece low profile',
    construction: 'one-piece',
    style: 'elongated',
    width: 0.38,
    depth: 0.6,
    baseWidth: 0.33,
    baseDepth: 0.5,
    baseStyle: 'skirted',
    taper: 0.14,
    tankType: 'attached',
    tankWidth: 0.43,
    tankHeight: 0.28,
    tankDepth: 0.2,
    tankCornerRadius: 0.045,
    tankTaper: 0.12,
    tankLidThickness: 0.012,
  },
  {
    design: 'one-piece-square',
    label: 'One-piece soft square',
    construction: 'one-piece',
    style: 'square',
    width: 0.38,
    depth: 0.55,
    baseWidth: 0.35,
    baseDepth: 0.5,
    baseStyle: 'skirted',
    taper: 0.05,
    tankType: 'attached',
    tankWidth: 0.38,
    tankHeight: 0.36,
    tankDepth: 0.16,
    tankCornerRadius: 0.008,
    tankTaper: 0,
    tankLidThickness: 0.014,
  },
  {
    design: 'one-piece-sculpted',
    label: 'One-piece sculpted',
    construction: 'one-piece',
    style: 'rounded',
    width: 0.37,
    depth: 0.57,
    baseWidth: 0.29,
    baseDepth: 0.46,
    baseStyle: 'pedestal',
    taper: 0.25,
    tankType: 'attached',
    tankWidth: 0.39,
    tankHeight: 0.32,
    tankDepth: 0.18,
    tankCornerRadius: 0.04,
    tankTaper: 0.15,
    tankLidThickness: 0.012,
  },
] as const
export const isOnePiece = (n: FloorStandingToiletNode) =>
  (n.construction ?? (n.design.startsWith('one-piece') ? 'one-piece' : 'two-piece')) === 'one-piece'
export function toiletLayout(n: FloorStandingToiletNode) {
  const external = n.tankType !== 'concealed'
  const rearSpace = n.tankType === 'attached' ? n.tankDepth : 0
  const tankBottom =
    n.tankType === 'attached'
      ? n.mountingHeight + (isOnePiece(n) ? 0.005 : n.couplingGap)
      : Math.max(
          n.mountingHeight + 0.08,
          n.tankType === 'high-level' ? Math.max(1.5, n.tankBottom) : n.tankBottom,
        )
  return {
    external,
    rearSpace,
    projection: n.depth + rearSpace,
    tankBottom,
    totalHeight: Math.max(
      n.mountingHeight +
        n.seatThickness +
        (n.lidEnabled ? (n.lidOpen ? n.depth + 0.005 : 0.015) : 0),
      external ? tankBottom + n.tankHeight + n.tankLidThickness : 0,
    ),
  }
}
