import { useScene, clearSceneHistory, type AnyNodeId } from "@pascal-app/core";
import { readStreetProjectFromSite } from "../src/host/street-project-persistence";
import { createStreetScenario, selectStreetScenario, redesignStreetSectionLayout, redesignStreetSectionStyle, lockStreetScenarioSection, suppressStreetScenarioInventory } from "../src/host/street-scenario-command";
import { compileStreetProject } from "../src/effective-street-model";
import { readResolvedCurrentRoad } from "../src/street-project-compatibility";
import { streetInventoryItemId } from "../src/domain/street-scenario";
const base="http://localhost:3002/api/scenes";
const sourceResponse=await fetch(`${base}/${process.argv[2] ?? "48a682c9e814"}`,{signal:AbortSignal.timeout(60000)});
if(!sourceResponse.ok)throw Error(await sourceResponse.text());
const source=await sourceResponse.json();
const create=await fetch(base,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:"Step 46 effective model acceptance",graph:source.graph}),signal:AbortSignal.timeout(60000)});
if(!create.ok)throw Error(await create.text());
const saved=await create.json();
useScene.setState({...source.graph,readOnly:false});
const site=Object.values(useScene.getState().nodes).find(n=>n.type === "site")!;
const read=()=>readStreetProjectFromSite(useScene.getState().nodes[site.id])!;
let doc=read();
const baselineId=doc.project.activeBaselineRevisionId,baselinesBefore=JSON.stringify(doc.project.baselineRevisions),sourcesBefore=JSON.stringify(doc.project.sourceReferences);
const roadId=Object.keys(doc.project.baselineRevisions[baselineId]!.roads)[0]!;
const baselineRoad=readResolvedCurrentRoad(doc.project,baselineId,roadId);
const edgeId=Object.keys(baselineRoad.edges).find(id=>baselineRoad.edges[id]!.sectionLayout)!;
const sectionId=`section:${edgeId}`,layout=structuredClone(baselineRoad.edges[edgeId]!.sectionLayout!);
const a=createStreetScenario(site.id,doc.project.revision,"Concrete walking proposal")!;
layout.intervals[0]!.leftBands[0]!.width=4;
redesignStreetSectionLayout(site.id,read().project.revision,roadId,sectionId,layout,"More walking space");
redesignStreetSectionStyle(site.id,read().project.revision,roadId,sectionId,{surfaceMaterial:"concrete"},"Concrete pavement proposal");
lockStreetScenarioSection(site.id,read().project.revision,roadId,sectionId,true,"Pin reviewed section design");
let lockedEditRejected=false;
try {redesignStreetSectionStyle(site.id,read().project.revision,roadId,sectionId,{surfaceMaterial:"asphalt"},"Change locked material");} catch {lockedEditRejected=true;}
const crossing=baselineRoad.osmLaneConnectivity[0]!;
if(!crossing)throw Error("QA fixture requires mapped connectivity");
const target={category:"laneConnectivity",roadId,itemId:streetInventoryItemId("laneConnectivity",crossing)};
const before=useScene.getState().nodes;
clearSceneHistory();
suppressStreetScenarioInventory(site.id,read().project.revision,target,true,"Suppress mapped connectivity in proposal");
const undoCount=useScene.temporal.getState().pastStates.length;
useScene.temporal.getState().undo();const undoRestored=JSON.stringify(useScene.getState().nodes)===JSON.stringify(before);
suppressStreetScenarioInventory(site.id,read().project.revision,target,true,"Suppress mapped connectivity in proposal");
const b=createStreetScenario(site.id,read().project.revision,"Asphalt alternative")!;
redesignStreetSectionStyle(site.id,read().project.revision,roadId,sectionId,{surfaceMaterial:"asphalt"},"Alternative pavement");
doc=read();
const one=compileStreetProject(doc.project,baselineId,a),two=compileStreetProject(doc.project,baselineId,b),baseline=compileStreetProject(doc.project,baselineId);
const roadA=one.effective.roads[roadId]!,roadB=two.effective.roads[roadId]!;
const unchangedLaneWidth=roadA.stylePresets[roadA.edges[edgeId]!.styleId]!.laneWidth===roadB.stylePresets[roadB.edges[edgeId]!.styleId]!.laneWidth;
const scenarioWidthA=roadA.edges[edgeId]!.sectionLayout!.intervals[0]!.leftBands[0]!.width,scenarioWidthB=roadB.edges[edgeId]!.sectionLayout!.intervals[0]!.leftBands[0]!.width;
selectStreetScenario(site.id,doc.project.revision,a);doc=read();
const state=useScene.getState();
const graph={...source.graph,nodes:state.nodes,rootNodeIds:state.rootNodeIds,collections:state.collections};
const update=await fetch(`${base}/${saved.id}`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({graph,expectedVersion:saved.version}),signal:AbortSignal.timeout(60000)});
if(!update.ok)throw Error(await update.text());
const reopened=await (await fetch(`${base}/${saved.id}`,{signal:AbortSignal.timeout(60000)})).json();
const persisted=readStreetProjectFromSite(reopened.graph.nodes[site.id])!;
const result={sceneId:saved.id,scenarioA:a,scenarioB:b,baselineId,roadId,edgeId,sectionId,scenarioWidthA,scenarioWidthB,unchangedLaneWidth,scenarioConnectivityA:roadA.osmLaneConnectivity.length,scenarioConnectivityB:roadB.osmLaneConnectivity.length,baselineConnectivity:baseline.effective.roads[roadId]!.osmLaneConnectivity.length,independentCompilation:JSON.stringify(one.roads[roadId]!.canonicalFloorplan)!==JSON.stringify(two.roads[roadId]!.canonicalFloorplan),lockedEditRejected,undoCount,undoRestored,baselineUnchanged:JSON.stringify(doc.project.baselineRevisions)===baselinesBefore,sourcesUnchanged:JSON.stringify(doc.project.sourceReferences)===sourcesBefore,reopenedSame:JSON.stringify(persisted)===JSON.stringify(doc)};
if(Object.values(result).includes(false))throw Error(JSON.stringify(result));
await Bun.write("packages/streetscape/docs/fixtures/effective-model-api-result.json",JSON.stringify(result,null,2)+"\n");
console.log(result);
