import { useScene, clearSceneHistory } from "@pascal-app/core";
import { readStreetProjectFromSite } from "../src/host/street-project-persistence";
import { redesignStreetSectionLayout, selectStreetScenario } from "../src/host/street-scenario-command";
import { RoadNetworkNode } from "../src/schema";
const url = "http://localhost:3002/api/scenes/48a682c9e814";
const saved = await (await fetch(url)).json();
useScene.setState({...saved.graph, readOnly:false});
const site = Object.values(useScene.getState().nodes).find(n => n.type === "site")!;
const read = () => readStreetProjectFromSite(useScene.getState().nodes[site.id])!;
let doc = read();
const beforeBaselines = JSON.stringify(doc.project.baselineRevisions);
const beforeSources = JSON.stringify(doc.project.sourceReferences);
const scenarioId = doc.project.activeScenarioId!;
const road = Object.values(doc.project.baselineRevisions[doc.project.activeBaselineRevisionId]!.roads)[0]!;
const sectionId = Object.keys((road.data as {sections:object}).sections)[0]!;
const nodeId = doc.projection.bindings.find(b => b.category === "roads")!.nodeIds[0]!;
const getRoad = () => RoadNetworkNode.parse((useScene.getState().nodes as Record<string, unknown>)[nodeId]);
const edgeId = Object.keys(getRoad().edges).find(id => getRoad().edges[id]!.sectionLayout)!;
const layout = structuredClone(getRoad().edges[edgeId]!.sectionLayout!);
if (!layout.intervals[0]!.rightBands.some(b => b.kind === "protected-cycling")) layout.intervals[0]!.rightBands.push({id:"qa-design-cycling",kind:"protected-cycling",width:2});
redesignStreetSectionLayout(site.id,doc.project.revision,road.id,sectionId,layout,"Protected cycling design proposal");
const designEdges = JSON.stringify(getRoad().edges);
clearSceneHistory();
selectStreetScenario(site.id,read().project.revision,null);
const baselineLayout = getRoad().edges[edgeId]!.sectionLayout!;
const baselineRestored = baselineLayout.intervals[0]!.leftBands[0]!.width === 2 && !baselineLayout.intervals[0]!.rightBands.some(b => b.kind === "protected-cycling");
useScene.temporal.getState().undo();
const undoRestored = JSON.stringify(getRoad().edges) === designEdges && read().project.activeScenarioId === scenarioId;
doc = read();
const state = useScene.getState();
const graph = {nodes:state.nodes,rootNodeIds:state.rootNodeIds,collections:state.collections,materials:saved.graph.materials,installedPlugins:saved.graph.installedPlugins};
const response = await fetch(url,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({graph,expectedVersion:saved.version})});
if (!response.ok) throw Error(await response.text());
const reopened = await (await fetch(url)).json();
const persisted = readStreetProjectFromSite(reopened.graph.nodes[site.id])!;
const result = {sceneId:saved.id,baselineUnchanged:JSON.stringify(doc.project.baselineRevisions)===beforeBaselines,sourcesUnchanged:JSON.stringify(doc.project.sourceReferences)===beforeSources,baselineRestored,undoRestored,designWidth:layout.intervals[0]!.leftBands[0]!.width,cyclingAdded:true,reopenedSame:JSON.stringify(persisted)===JSON.stringify(doc),scenarioName:doc.project.scenarios[scenarioId]!.name};
if (Object.values(result).includes(false)) throw Error(JSON.stringify(result));
await Bun.write("packages/streetscape/docs/fixtures/scenario-mode-api-result.json",JSON.stringify(result,null,2)+"\n");
console.log(result);
