import { readStreetProjectFromSite } from '../src/host/street-project-persistence';
import { verifyStreetProjectSnapshots } from '../src/source/osm-snapshot-project';
import { resolveEffectiveStreetModel } from '../src/effective-street-model';
const sceneId='cf0c9d718146';
const response=await fetch(`http://localhost:3002/api/scenes/${sceneId}`);
if(!response.ok)throw Error('Saved QA scene unavailable');
const saved=await response.json();
const owner=Object.values(saved.graph.nodes).find((n:any)=>n.type==='site');
const doc=readStreetProjectFromSite(owner);
if(!doc)throw Error('Saved street document missing');
const {project,snapshots}=await verifyStreetProjectSnapshots(doc.project);
const baseline=project.baselineRevisions[project.activeBaselineRevisionId]!;
if(!baseline.id.includes(':refresh:')||Object.keys(snapshots).length!==2)throw Error('Accepted refresh or immutable snapshots missing');
const effective=resolveEffectiveStreetModel(project,baseline.id,project.activeScenarioId);
const road=Object.values(effective.roads)[0]!;
const layout=Object.values(road.edges).find(e=>e.sectionLayout)?.sectionLayout;
if(layout?.intervals[0]?.leftBands[0]?.width!==4)throw Error('Saved locked design changed');
if(!Object.values(effective.features).some(f=>f.sourceFeatureId==='node/999'))throw Error('Added source lamp missing');
if(Object.values(project.scenarios).some(s=>s.baselineRevisionId!==baseline.id))throw Error('Scenario rebase not persisted');
const result={sceneId,revision:project.revision,baselineId:baseline.id,verifiedSnapshots:Object.keys(snapshots).length,lockedWalkingWidth:4,sourceLampRetained:true,allScenariosRebased:true,savedDocumentVerified:true};
await Bun.write('packages/streetscape/docs/fixtures/source-merge-saved-result.json',JSON.stringify(result,null,2)+'\n');
console.log(result);
